/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdd.ui;

import bdd.Aplicativo;
import bdd.DatosPermiso;
import bdd.DatosPersonaPregunta;
import bdd.DatosPersonas;
import bdd.DatosPersonasYPermisos;
import bdd.DatosSolicitudPermiso;
import bdd.Persona;
import bdd.PersonaPregunta;
import bdd.Pregunta;
import bdd.RolNegocio;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fede2
 */
public class ContraseñaOlvidada extends javax.swing.JFrame {
    private final Persona usuario;
    private final DatosPersonas datosPersonas;
    private final DatosPermiso datosPermiso;
    private final DatosPersonasYPermisos datosPersonasYPermisos;
    private final DatosSolicitudPermiso datosSolicitudPermiso;
    private final List<Pregunta> opcionesPreguntas;
    private final DatosPersonaPregunta datosPersonaPregunta;
    private final List<RolNegocio> opcionesRolNegocio;
    private final List<Aplicativo> opcionesAplicativo;

    
    public ContraseñaOlvidada(Persona Usuario, DatosPersonas DatosPersonas, DatosPersonaPregunta datosPersonaPregunta, DatosPermiso datosPermiso, DatosPersonasYPermisos datosPersonasYPermisos, DatosSolicitudPermiso datosSolicitudPermiso, List<Pregunta> preguntas, List<RolNegocio> roles,
                         List<Aplicativo> aplicativos) {
        
        initComponents();
        
        this.usuario = Usuario;
        this.datosPersonas = DatosPersonas;
        this.datosPermiso = datosPermiso;
        this.opcionesPreguntas = preguntas;
        this.datosPersonaPregunta = datosPersonaPregunta;
        this.datosPersonasYPermisos = datosPersonasYPermisos;
        this.datosSolicitudPermiso = datosSolicitudPermiso;
        this.opcionesRolNegocio = roles;
        this.opcionesAplicativo = aplicativos;        
                
        opcionesPreguntas.forEach(x -> {
            Preguntas.addItem(x.getPregunta());
        });
    }
    
    public void mostrarError(String mensaje) {
        var f = new ErrorDialog(this, true, mensaje);
        f.setVisible(true);
    }
    
    public boolean ContraOlvidada() throws SQLException {
        
        if (String.valueOf(Contraseña_Nueva.getPassword()).isEmpty()) {
            mostrarError("El campo Contraseña nueva no puede estar vacío");
            return false;
        }
        
        if (Preguntas.getSelectedIndex() == 0) {
            mostrarError("Seleccione una pregunta de seguridad");
            return false;
        }
        
        Pregunta pregunta = opcionesPreguntas.get(Preguntas.getSelectedIndex() - 1);
        String respuesta = Respuesta.getText().trim();
        
        if (respuesta.isEmpty()) {
            mostrarError("El campo respuesta no puede estar vacío");
            return false;
        }
        
        PersonaPregunta UsrPreg = datosPersonaPregunta.getByUserId(usuario.userId);
        
        if(UsrPreg != null && pregunta.getPregId() == UsrPreg.pregId){
            if (UsrPreg.respuesta.equals(respuesta)) {
                System.out.println("llegue");
                String password = String.valueOf(Contraseña_Nueva.getPassword());
                
                usuario.setPassword(password);
                this.datosPersonas.updateOrCreate(usuario);
                return true;
            } else {
                mostrarError("La respuesta es incorrecta");
            return false;
            }
        } else {
            mostrarError("Esa pregunta no fue respondida al registrarse");
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Preguntas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Respuesta = new javax.swing.JTextField();
        Botton = new javax.swing.JButton();
        Contraseña_Nueva = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Recuperar Contraseña");

        Preguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel2.setText("Seleccione su pregunta de seguridad.");

        jLabel3.setText("Ingrese su respuesta.");

        Botton.setText("Hecho");
        Botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonActionPerformed(evt);
            }
        });

        jLabel4.setText("Contraseña nueva");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Preguntas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Botton)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 312, Short.MAX_VALUE))
                    .addComponent(Respuesta)
                    .addComponent(Contraseña_Nueva))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña_Nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Botton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonActionPerformed
        // TODO add your handling code here:
        boolean exito = false;
        try {
            // TODO add your handling code here:
            exito = ContraOlvidada();
        } catch (SQLException ex) {
            Logger.getLogger(ContraseñaOlvidada.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (exito){
            System.out.println("llegue 2");
            var framelogin = new LoginPersonas(datosPersonas, datosPersonaPregunta, datosPermiso, datosPersonasYPermisos, datosSolicitudPermiso, opcionesPreguntas, opcionesRolNegocio, opcionesAplicativo);
            framelogin.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_BottonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botton;
    private javax.swing.JPasswordField Contraseña_Nueva;
    private javax.swing.JComboBox<String> Preguntas;
    private javax.swing.JTextField Respuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
